# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 375)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(470, 0))
        self.centralwidget.setStyleSheet("QWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"     font: normal 12pt \"Segoe UI\";\n"
" }\n"
"\n"
"\n"
"QPlaneTextEdit{\n"
"    font: normal 12pt \"Segoe UI\";\n"
"    text-align: center;\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px; \n"
"\n"
"    color: rgb(27, 29, 35);\n"
"\n"
"}\n"
"QPlaneTextEdit:hover{\n"
"    border: 2px solid #40a7e3;\n"
"}\n"
"\n"
" /* CHEK_BOX */\n"
"QCheckBox{\n"
"    padding: 5px;\n"
"}\n"
"\n"
" /* LINE EDIT */\n"
"QLineEdit{\n"
"    font: normal 12pt \"Segoe UI\";\n"
"    text-align: center;\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid #40a7e3;\n"
"}\n"
"\n"
"\n"
"/* PASH_BUTTON */\n"
"QPushButton {    \n"
"    font: normal 12pt \"Segoe UI\";\n"
"    text-align: center;\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #40a7e3;\n"
"     \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
" /* PROGRESS BAR */\n"
"QProgressBar {\n"
"\n"
"    background-color: #16191d;\n"
"\n"
"    \n"
"    border-radius: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"     background-color: #343b47;\n"
"background-color: rgb(39, 44, 54);\n"
"    border: 2px solid #1f232a;\n"
"     border-radius: 5px;\n"
" \n"
"}\n"
"\n"
"\n"
"/* COMBO BOX */\n"
"QComboBox{\n"
"    font: normal 12pt \"Segoe UI\";\n"
"    text-align: center;\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"     /*height: 15px;*/\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #40a7e3;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/16x16/icon/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    image: url(:/16x16/icon/cil-arrow-top.png);\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.message_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.message_text_edit.setStyleSheet("    font: normal 12pt \"Segoe UI\";\n"
"    text-align: center;\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;")
        self.message_text_edit.setObjectName("message_text_edit")
        self.verticalLayout.addWidget(self.message_text_edit)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.name_line_edit.setText("")
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.project_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.project_combo_box.setObjectName("project_combo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.project_combo_box)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.path_layout = QtWidgets.QVBoxLayout()
        self.path_layout.setSpacing(7)
        self.path_layout.setObjectName("path_layout")
        self.path_button = QtWidgets.QPushButton(self.centralwidget)
        self.path_button.setMinimumSize(QtCore.QSize(100, 0))
        self.path_button.setObjectName("path_button")
        self.path_layout.addWidget(self.path_button)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.path_layout)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.wareframe_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.wareframe_check_box.setMinimumSize(QtCore.QSize(0, 20))
        self.wareframe_check_box.setMaximumSize(QtCore.QSize(471, 16777215))
        self.wareframe_check_box.setText("")
        self.wareframe_check_box.setObjectName("wareframe_check_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wareframe_check_box)
        self.verticalLayout.addLayout(self.formLayout)
        self.messaje_button = QtWidgets.QPushButton(self.centralwidget)
        self.messaje_button.setMinimumSize(QtCore.QSize(0, 0))
        self.messaje_button.setStyleSheet("")
        self.messaje_button.setObjectName("messaje_button")
        self.verticalLayout.addWidget(self.messaje_button)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Message text:"))
        self.label_2.setText(_translate("MainWindow", "Asset name:"))
        self.label_3.setText(_translate("MainWindow", "Project:"))
        self.label_4.setText(_translate("MainWindow", "Path to video:"))
        self.path_button.setText(_translate("MainWindow", "add file"))
        self.label_5.setText(_translate("MainWindow", "Wireframe tag:"))
        self.messaje_button.setText(_translate("MainWindow", "Send message"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
